### PR TITLE
left-justify condition messages

### LINKED ISSUE #617: use indentation to structure catalog output
The issue catalog currently respects newlines outputted by `conditionMessage()` methods. These are especially common with warnings and errors built with rlang:

``` r
library(tidymodels)

rec_spec <- recipe(mpg ~ ., data = mtcars) %>%
  step_mutate(vs = gfdhdfds + 4)

lm_spec <- linear_reg()

wf_spec <- workflow(rec_spec, lm_spec)

folds <- vfold_cv(mtcars, v = 2)

res <- fit_resamples(wf_spec, folds)
#> → 1 | error: Error in `step_mutate()`:
#> Caused by error in `dplyr::mutate()`:
#> ℹ In argument: `vs = gfdhdfds + 4`.
#> Caused by error:
#> ! object 'gfdhdfds' not found
#> There were issues with some computations   1: x2
#> 
#> Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
#> information.
```

Especially without cli formatting (as in reprexes), it can be hard to tell when one issue ends and the other begins. We could left-justify each condition message, like:

```r
#> → 1 | error: Error in `step_mutate()`:
#>              Caused by error in `dplyr::mutate()`:
#>              ℹ In argument: `vs = gfdhdfds + 4`.
#>              Caused by error:
#>              ! object 'gfdhdfds' not found
#> There were issues with some computations   1: x2
#> 
#> Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
#> information.
```

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #617.

The previous catalog output:

``` r
library(tidymodels)

become_flustered <- function(x) {
  cli::cli_warn(c("hmmm what's happening", "uuuhhHhH"))
  cli::cli_abort(c("aHHHksdjvndiuf", "!" = "),:"))
  x
}

res <- 
  fit_resamples(
    linear_reg(),
    mpg ~ .,
    bootstraps(mtcars, 10),
    control = control_resamples(extract = become_flustered)
  )
#> → A | warning: hmmm what's happening
#> uuuhhHhH
#> → B | error: aHHHksdjvndiuf
#> ! ),:
#> There were issues with some computations   A: x10   B: x10
```

Would now look like:

``` r
res <- 
  fit_resamples(
    linear_reg(),
    mpg ~ .,
    bootstraps(mtcars, 10),
    control = control_resamples(extract = become_flustered)
  )
#> → A | warning: hmmm what's happening
#>                uuuhhHhH
#> → B | error:   aHHHksdjvndiuf
#>                ! ),:
#> There were issues with some computations   A: x10   B: x10
```

Example with a more likely failure, from a recipe:

``` r
library(tidymodels)

res <- 
  fit_resamples(
    linear_reg(),
    recipe(mpg ~ ., data = mtcars) %>% step_mutate(vs = gfdhdfds + 4),
    vfold_cv(mtcars, v = 2)
  )
#> → A | error:   Error in `step_mutate()`:
#>                Caused by error in `dplyr::mutate()`:
#>                ℹ In argument: `vs = gfdhdfds + 4`.
#>                Caused by error:
#>                ! object 'gfdhdfds' not found
#> There were issues with some computations   A: x2
#> 
#> Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
#> information.
```

This opts to allot 7 characters to "error" or "warning" regardless of which will be printed so that the condition messages are always left-justified even if some are errors and others are warnings.

The justification code here is pretty scrappy, pending `r-lib/cli#229`.

### CODE REVIEW

File: R/logging.R [hunk 1]
```diff
@@ -187,8 +187,12 @@ tune_catalog <- function(issues) {
 
       # construct issue summary
       color <- if (current$type == "warning") {cli::col_yellow} else {cli::col_red}
```
Comment (EmilHvitfeldt) [inline R/logging.R:189]: This is not part of the changes, but it is in the same code chunk so I hope you are okay with this change. I find this easier to read, and it matches with our style https://style.tidyverse.org/syntax.html#inline-statements

```suggestion
      color <- if (current$type == "warning") cli::col_yellow else cli::col_red
```

File: R/logging.R [hunk 2]
```diff
@@ -187,8 +187,12 @@ tune_catalog <- function(issues) {
...
+      pad <- nchar(pull(res[issue, "id"])) + 14L
+      justify <- paste0("\n", paste0(rep("\u00a0", pad), collapse = ""))
```
Comment (EmilHvitfeldt) [inline R/logging.R:191]:
```suggestion
      justify <- paste0("\n", strrep("\u00a0", pad))
```

File: R/logging.R [hunk 3]
```diff
@@ -187,8 +187,12 @@ tune_catalog <- function(issues) {
...
+      note <- gsub("\n", justify, current$note)
+      if (current$type == "error") {note <- paste0("\u00a0\u00a0", note)}
```
Comment (EmilHvitfeldt) [inline R/logging.R:193]: In line with https://style.tidyverse.org/syntax.html#indenting

```suggestion
      if (current$type == "error") {
        note <- paste0("\u00a0\u00a0", note)
      }
```

File: R/logging.R [hunk 4]
```diff
@@ -187,8 +187,12 @@ tune_catalog <- function(issues) {
...
       msg <- glue::glue(
-        "{color(cli::style_bold(lbls[pull(res[issue, 'id'])]))} | {color(current$type)}: {current$note}"
+        "{color(cli::style_bold(lbls[pull(res[issue, 'id'])]))} | {color(current$type)}: {note}"
```
Comment (EmilHvitfeldt) [inline R/logging.R:195]: Correct me if I'm wrong, but isn't this a way to split a glue across lines without affecting the output?

```suggestion
        "{color(cli::style_bold(lbls[pull(res[issue, 'id'])]))} | \\
        {color(current$type)}: {note}"
```

File: R/logging.R [hunk 5]
```diff
@@ -187,8 +187,12 @@ tune_catalog <- function(issues) {
 
       # construct issue summary
       color <- if (current$type == "warning") {cli::col_yellow} else {cli::col_red}
+      pad <- nchar(pull(res[issue, "id"])) + 14L
```
Comment (EmilHvitfeldt) [inline R/logging.R:190]: I would like a comment here describing where this 14 comes from, otherwise it turns into a magic number 😄

**Review by EmilHvitfeldt — COMMENTED** [review]
I love this change, few minor comments!

**Review by EmilHvitfeldt — APPROVED** [review]
Looking sharp!
