### PR TITLE
Fix metric checking for quantile regression

### LINKED ISSUE #1186: check_metrics_arg() fails for quantile regression metrics
``` r
library(tidymodels)
library(ordered)
library(future)

plan("multisession")

set.seed(1215)
ames_split <- 
  ames |> 
  select(Latitude, Sale_Price) |> 
  initial_split(strata = Sale_Price)
ames_train <- training(ames_split)
ames_test <- testing(ames_split)
ames_rs <- vfold_cv(ames_train, strata = Sale_Price)

qnt_lvls <- c(0.05, 0.25, 0.5, 0.75, 0.95)

nnet_spec <- 
  mlp(hidden_units = tune(), penalty = tune(), epochs = 10) |> 
  set_mode("quantile regression", quantile_levels = qnt_lvls) |> 
  set_engine("qrnn", method = "adam")

nnet_rec <- recipe(Sale_Price ~ ., data = ames_train) |> 
  step_normalize(all_predictors())

nnet_wflow <- workflow(nnet_rec, nnet_spec)
qnt_set <- metric_set(weighted_interval_score)

# works with no metric set input
set.seed(971)
nnet_res <- 
  nnet_wflow |> 
  tune_grid(
    resamples = ames_rs,
    grid = 3 
    # metrics = qnt_set
  )

# whomp whomp
set.seed(971)
nnet_res <- 
  nnet_wflow |> 
  tune_grid(
    resamples = ames_rs,
    grid = 3,
    metrics = qnt_set
  )
#> Error in `tune_grid()`:
#> ! The `metrics` argument should be the results of
#>   `yardstick::metric_set()`.
```

<sup>Created on 2026-04-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by topepo**
Closes #1186

### CODE REVIEW

File: R/metric-selection.R [hunk 1]
```diff
@@ -328,23 +328,30 @@ check_metrics_arg <- function(mtr_set, wflow, ..., call = rlang::caller_env()) {
     )
 
     return(mtr_set)
+  } else {
```
Comment (hfrick) [inline R/metric-selection.R]: we don't need this `else` here because the `if` path always ends with `return()`

File: R/metric-selection.R [hunk 2]
```diff
@@ -328,23 +328,30 @@ check_metrics_arg <- function(mtr_set, wflow, ..., call = rlang::caller_env()) {
...
-  if (
-    !is_numeric_metric_set && !is_class_prob_metric_set && !is_surv_metric_set
-  ) {
+  if (mode == "regression" && !is_numeric_metric_set) {
     cli::cli_abort(
-      "The {.arg metrics} argument should be the results of
-                   {.fn yardstick::metric_set}.",
+      "The parsnip model has {.code mode} value of {.val {mode}},
+                   but the {.arg metrics} is a metric set for a
+                   different model mode.",
```
Comment (hfrick) [inline R/metric-selection.R]:
```suggestion
      "The parsnip model has {.code mode} value of {.val {mode}},
       but {.arg metrics} is a metric set for a different model mode.",
```

The "the" read a bit weird to me. Plus bonus formatting :) I'd remove the "the" from the other error messages too. If you are feeling fancy, this would also be an opportunity to show the actual class of the metrics set rather than just say "it's for a different mode".

File: tests/testthat/_snaps/metric-args.md [hunk 3]
```diff
@@ -289,3 +297,27 @@
...
+      A metric set, consisting of:
+      - `weighted_interval_score()`, a quantile metric | direction: minimize
+
+---
+
+    Code
+      check_metrics_arg(metric_set(rmse), wflow)
+    Condition
+      Error:
+      ! The parsnip model has `mode` value of "quantile regression", but the `metrics` is a metric set for a different model mode.
```
Comment (hfrick) [inline tests/testthat/_snaps/metric-args.md]: "the metrics is" is what motivated my suggestion above

**Review by hfrick — APPROVED** [review]
