### PR TITLE
Compute grid info dplyr

### LINKED ISSUE #959: bug in refactored `compute_grid_info()`
After merging #957, we saw the following failures on extratests over the weekend:

```
══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Failure ('test-mars-tuning.R:63:3'): tuning for mars() -- submodels *and* 
mars_metrics$.config (`actual`) not equal to paste0("Preprocessor1_Model", 1:7) (`expected`).

    actual                 | expected                  
[1] "Preprocessor1_Model1" | "Preprocessor1_Model1" [1]
[2] "Preprocessor1_Model1" - "Preprocessor1_Model2" [2]
[3] "Preprocessor1_Model2" - "Preprocessor1_Model3" [3]
[4] "Preprocessor1_Model2" - "Preprocessor1_Model4" [4]
[5] "Preprocessor1_Model3" - "Preprocessor1_Model5" [5]
[6] "Preprocessor1_Model4" - "Preprocessor1_Model6" [6]
[7] "Preprocessor1_Model5" - "Preprocessor1_Model7" [7]

── 2. Failure ('test-mars-tuning.R:68:3'): tuning for mars() -- submodels *and* 
count(mars_preds, .row, .config)$n (`actual`) not equal to rep(1L, 5537) (`expected`).

       actual | expected       
   [4] 1      | 1        [1]   
   [5] 1      | 1        [2]   
   [6] 2      - 1        [3]   
   [7] 2      - 1        [4]   
```

Some additional trickiness here in grids that are partially regular and partially not so.

### PR DESCRIPTION
**Pull request by topepo**
Closes #959.

A rework with Simon of #960

The grids are sorted in the new version, so there were some changes to the expected results.

### CODE REVIEW

File: R/grid_helpers.R [hunk 1]
```diff
@@ -318,50 +318,71 @@ compute_grid_info <- function(workflow, grid) {
...
+  # preprocessing candidate set, make an iterator for the model candidate sets
+  # (if any)
+
+  res <-
+    res %>%
+    dplyr::group_nest(.iter_preprocessor, keep = TRUE) %>%
+    dplyr::mutate(
+      .iter_config = purrr::map(data, make_iter_config),
+      .model = purrr::map(data, ~ tibble::tibble(.iter_model = seq_len(nrow(.x)))),
+      .num_models = purrr::map_int(.model, nrow)
```
Comment (topepo) [inline R/grid_helpers.R:361]: This is needed for `res$.msg_model` (and is removed later)

File: R/grid_helpers.R [hunk 2]
```diff
@@ -318,50 +318,71 @@ compute_grid_info <- function(workflow, grid) {
...
+    ) %>%
+    dplyr::select(-.iter_preprocessor) %>%
+    tidyr::unnest(cols = c(data, .model, .iter_config)) %>%
+    dplyr::select(-.lab_pre) %>%
+    dplyr::relocate(dplyr::starts_with(".iter"))
```
Comment (topepo) [inline R/grid_helpers.R:366]: This (and another `relocate` below) should help with column ordering stability ~in case~ we refactor again.

File: R/grid_helpers.R [hunk 3]
```diff
@@ -318,50 +318,71 @@ compute_grid_info <- function(workflow, grid) {
...
+  syms_mod <- rlang::syms(parameters_model$id)
+
+  # ----------------------------------------------------------------------------
+  # Create an order of execution to train the preprocessor (if any). This will
+  # define a loop over any preprocessing tuning parameter combinations.
   if (any_parameters_preprocessor) {
-    res$.iter_preprocessor <- seq_len(nrow(res))
+    pp_df <-
+      dplyr::distinct(res, !!!syms_pre) %>%
+      dplyr::arrange(!!!syms_pre) %>%
```
Comment (topepo) [inline R/grid_helpers.R:330]: This will make the ordering of the preprocessors predictable. Previously, it would order them as-is. It's no big deal, but someone might wonder why `deg_free = 10` is executed before `deg_free=2`. 

This is why there are several `sort()` calls in the unit tests.

File: tests/testthat/test-grid_helpers.R [hunk 4]
```diff
@@ -212,6 +221,12 @@ test_that("compute_grid_info - recipe and model (with and without submodels)", {
       list(trees = c(1L, 1000L))
     )
   )
+  expect_equal(
```
Comment (topepo) [inline tests/testthat/test-grid_helpers.R:224]: We can't be too paranoid about this.

File: tests/testthat/test-grid_helpers.R [hunk 5]
```diff
@@ -185,25 +189,30 @@ test_that("compute_grid_info - recipe and model (with and without submodels)", {
   # use grid_regular to (partially) trigger submodel trick
   set.seed(1)
   param_set <- extract_parameter_set_dials(wflow)
-  grid <- bind_rows(grid_regular(param_set), grid_space_filling(param_set))
+  grid <-
```
Comment (topepo) [inline tests/testthat/test-grid_helpers.R:192]: I was going to add more tests for unbalanced grids but this one covers it well.

File: tests/testthat/test-grid_helpers.R [hunk 6]
```diff
@@ -185,25 +189,30 @@ test_that("compute_grid_info - recipe and model (with and without submodels)", {
...
     unique(res$.msg_preprocessor),
     paste0("preprocessor ", 1:5, "/5")
   )
-  expect_equal(res$trees, c(rep(max(grid$trees), 10), 1))
+  expect_equal(sort(res$trees), sort(c(rep(max(grid$trees), 10), 1)))
   expect_equal(unique(res$.iter_model), 1:3)
   expect_equal(
-    res$.iter_config[1:3],
+    res$.iter_config[res$.iter_preprocessor == 1],
     list(
```
Comment (simonpcouch) [inline tests/testthat/test-grid_helpers.R:206]: Your new enumeration is correct (and fixes the case where I had broken previously), but it does look like we're missing a `format_with_padding` still. When I run these tests with CRAN `compute_grid_info()`, I see:

```
── Failure (test-grid_helpers.R:204:3): compute_grid_info - recipe and model (with and without submodels) ──
res$.iter_config[res$.iter_preprocessor == 1] (`actual`) not equal to list(...) (`expected`).

    actual[[1]]             | expected[[1]]             
[1] "Preprocessor1_Model01" - "Preprocessor1_Model1" [1]
[2] "Preprocessor1_Model02" - "Preprocessor1_Model2" [2]
[3] "Preprocessor1_Model03" - "Preprocessor1_Model3" [3]
[4] "Preprocessor1_Model04" - "Preprocessor1_Model4" [4]

`actual[[2]]`:   "Preprocessor1_Model05" "Preprocessor1_Model06" "Preprocessor1_Model07"
`expected[[2]]`: "Preprocessor1_Model5"  "Preprocessor1_Model6"  "Preprocessor1_Model7" 

`actual[[3]]`:   "Preprocessor1_Model08" "Preprocessor1_Model09" "Preprocessor1_Model10"
`expected[[3]]`: "Preprocessor1_Model8"  "Preprocessor1_Model9"  "Preprocessor1_Model10"
```

File: R/grid_helpers.R [hunk 7]
```diff
@@ -318,50 +318,71 @@ compute_grid_info <- function(workflow, grid) {
...
-    "Preprocessor",
-    res_row$.iter_preprocessor,
-    "_Model",
-    format_with_padding(models)
-  )
+make_iter_config <- function(dat) {
+  # Compute labels for the models *within* each preprocessing loop.
+  num_submodels <- purrr::map_int(dat$.submodels, ~ length(unlist(.x)))
+  num_models <- sum(num_submodels + 1) # +1 for the model being trained
+  .mod_label <- paste0("Model", 1:num_models)
```
Comment (simonpcouch) [inline R/grid_helpers.R:382]:
```suggestion
  .mod_label <- paste0("Model", seq_len(num_models))
```

Comment (simonpcouch) [reply R/grid_helpers.R:382]: Would be curious if we could just add a `format_with_padding()` here, but I think that actually needs to happen outside of the loop since a different preprocessor might be paired with models that enum up to the tens / hundreds place.

**Review by simonpcouch — COMMENTED** [review]
Awesome. This fixes bugs I had introduced in the previous refactor and I find it more readable. 

We're just one `format_with_padding()` away from being there, though it's proven tricky to situate that in the right place given that each of those `.iter_config`s live inside of lists. I'm open to entertaining the argument that the padding is ultimately unneeded if you think that's the best way to move forward—those `.iter_config` indices can be reasonably separated using just "Preprocessor" and "_Model" already. In the case we're fine with that padding going away, consider this an "Approve" merge once we've noted the change in NEWS. Otherwise, a bit more work to do.

I just adjusted the ref in https://github.com/tidymodels/extratests/pull/227 to test this PR. I'm assuming it will fail with a `format_with_padding()` snap change but otherwise run fine.

File: R/grid_helpers.R (hunk 7 above)
Comment (topepo) [reply R/grid_helpers.R:382]: IT's pretty easy with `recipes::names0()`: https://github.com/tidymodels/tune/commit/2a78da3477efc77a4fe64e128fcf7318b4c8dfb2#diff-f8b62de58f2adfdb08f139a17fd26e3ddb0b7a0ab33909f5bbdb6fdb93ba7923L333

Comment (topepo) [reply R/grid_helpers.R:382]: I think that this will work in `make_iter_config()`; all the models within the preprocessor combination are present at that time.

Comment (topepo) [reply R/grid_helpers.R]: tidymodels/extratests/227 looks goo after the last commit.

**Review by simonpcouch — APPROVED** [review]
Nice, I see passing tests with the CRAN version, too! Let's merge this in.
