### PR TITLE
align `.config` entries in `tune_bayes()` output

### LINKED ISSUE #715: Extracting with `tune_bayes()` results in the same `.config` entry for each iteration
Hello,

when using bayes tuning and extracting with `tune::extract_fit_engine` (s. reprex: the oob error from a `ranger` model),
the corresponding `.config`-column of `.extracts` contains always the value `Preprocessor1_Model1` for each iteration instead of `Iter1, Iter2, ...` (compare the `.config`-column of `.metrics`). 

``` r
library(magrittr)
library(yardstick)

set.seed(1234)

d <- mtcars %>% tibble::as_tibble()

prep_rec <- recipes::recipe(mpg ~ . ,data = d) %>% 
  recipes::prep()


rsmpl <- rsample::bootstraps(data = d, times = 2)  


mod_spec <- parsnip::rand_forest() %>%
  parsnip::set_engine("ranger") %>%
  parsnip::set_mode("regression") %>% 
  parsnip::set_args(mtry = 2, trees = tune())


param_set <- hardhat::extract_parameter_set_dials(mod_spec)

extract_oob <- function(x) { 
  tune::extract_fit_engine(x)$prediction.error
}

res <- tune::tune_bayes(object       = mod_spec, 
                        preprocessor = formula(prep_rec),
                        resamples    = rsmpl, 
                        metrics      = metric_set(rmse),
                        iter         = 3, 
                        param_info   = param_set, 
                        control      = tune::control_bayes(seed      = 1234, 
                                                           save_pred = TRUE, 
                                                           extract   = extract_oob))

# within .metrics the.config distingushes among initial combinations 
# (Preprocessor1_XXX) and iterations
res %>% dplyr::select(id, .metrics, .iter) %>% tidyr::unnest(.metrics)
#> # A tibble: 16 × 7
#>    id         trees .metric .estimator .estimate .config              .iter
#>    <chr>      <int> <chr>   <chr>          <dbl> <chr>                <int>
#>  1 Bootstrap1   234 rmse    standard        2.43 Preprocessor1_Model1     0
#>  2 Bootstrap1   884 rmse    standard        2.40 Preprocessor1_Model2     0
#>  3 Bootstrap1  1902 rmse    standard        2.34 Preprocessor1_Model3     0
#>  4 Bootstrap1   572 rmse    standard        2.31 Preprocessor1_Model4     0
#>  5 Bootstrap1  1284 rmse    standard        2.40 Preprocessor1_Model5     0
#>  6 Bootstrap2   234 rmse    standard        3.09 Preprocessor1_Model1     0
#>  7 Bootstrap2   884 rmse    standard        3.28 Preprocessor1_Model2     0
#>  8 Bootstrap2  1902 rmse    standard        3.18 Preprocessor1_Model3     0
#>  9 Bootstrap2   572 rmse    standard        3.28 Preprocessor1_Model4     0
#> 10 Bootstrap2  1284 rmse    standard        3.25 Preprocessor1_Model5     0
#> 11 Bootstrap1  2000 rmse    standard        2.40 Iter1                    1
#> 12 Bootstrap2  2000 rmse    standard        3.30 Iter1                    1
#> 13 Bootstrap1  1903 rmse    standard        2.40 Iter2                    2
#> 14 Bootstrap2  1903 rmse    standard        3.25 Iter2                    2
#> 15 Bootstrap1   209 rmse    standard        2.44 Iter3                    3
#> 16 Bootstrap2   209 rmse    standard        3.07 Iter3                    3


# within .extracts the .config column always contains Preprocessor1_Model1
res %>% dplyr::select(id, .extracts, .iter) %>% tidyr::unnest(.extracts)
#> # A tibble: 16 × 5
#>    id         trees .extracts .config              .iter
#>    <chr>      <int> <list>    <chr>                <int>
#>  1 Bootstrap1   234 <dbl [1]> Preprocessor1_Model1     0
#>  2 Bootstrap1   884 <dbl [1]> Preprocessor1_Model2     0
#>  3 Bootstrap1  1902 <dbl [1]> Preprocessor1_Model3     0
#>  4 Bootstrap1   572 <dbl [1]> Preprocessor1_Model4     0
#>  5 Bootstrap1  1284 <dbl [1]> Preprocessor1_Model5     0
#>  6 Bootstrap2   234 <dbl [1]> Preprocessor1_Model1     0
#>  7 Bootstrap2   884 <dbl [1]> Preprocessor1_Model2     0
#>  8 Bootstrap2  1902 <dbl [1]> Preprocessor1_Model3     0
#>  9 Bootstrap2   572 <dbl [1]> Preprocessor1_Model4     0
#> 10 Bootstrap2  1284 <dbl [1]> Preprocessor1_Model5     0
#> 11 Bootstrap1  2000 <dbl [1]> Preprocessor1_Model1     1
#> 12 Bootstrap2  2000 <dbl [1]> Preprocessor1_Model1     1
#> 13 Bootstrap1  1903 <dbl [1]> Preprocessor1_Model1     2
#> 14 Bootstrap2  1903 <dbl [1]> Preprocessor1_Model1     2
#> 15 Bootstrap1   209 <dbl [1]> Preprocessor1_Model1     3
#> 16 Bootstrap2   209 <dbl [1]> Preprocessor1_Model1     3
```

<sup>Created on 2023-09-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #715.

### CODE REVIEW

File: R/tune_bayes.R [hunk 1]
```diff
@@ -432,6 +432,12 @@ tune_bayes_workflow <-
             ~ dplyr::mutate(., .config = paste0("Iter", i))
           )
         }
+        if (".extracts" %in% names(tmp_res)) {
+          tmp_res[[".extracts"]] <- purrr::map(
+            tmp_res[[".extracts"]],
+            ~ dplyr::mutate(., .config = paste0("Iter", i))
+          )
+        }
```
Comment (simonpcouch) [inline R/tune_bayes.R:440]: The substance of the PR is here and in the untouched lines above; we just need to make the same `mutate()` happen in `.extracts` that happened already for `.metrics` and `.predictions`.

**Review by EmilHvitfeldt — APPROVED** [review]
looking sharp!
