### PR TITLE
Error message for missing assessment set rows at prediction time

### LINKED ISSUE #241: Warn user about using step_naomit with tuning
Add a warning or improve error message when using `step_naomit()` (and other row filtering step functions?) before tuning.

Here's an example with `penguins`:

``` r
suppressPackageStartupMessages(library(tidymodels))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(palmerpenguins))

penguins %>%
  summarise(across(.fns=list(n_miss = ~ sum(is.na(.x))))) %>%
  glimpse()
#> Rows: 1
#> Columns: 7
#> $ species_n_miss           <int> 0
#> $ island_n_miss            <int> 0
#> $ bill_length_mm_n_miss    <int> 2
#> $ bill_depth_mm_n_miss     <int> 2
#> $ flipper_length_mm_n_miss <int> 2
#> $ body_mass_g_n_miss       <int> 2
#> $ sex_n_miss               <int> 11

set.seed(123)
peng_split <- initial_split(penguins, 
                            strata = species)

peng_train <- training(peng_split)
peng_test  <- testing(peng_split)


folds <- vfold_cv(peng_train, v = 6)
folds
#> #  6-fold cross-validation 
#> # A tibble: 6 x 2
#>   splits           id   
#>   <named list>     <chr>
#> 1 <split [215/43]> Fold1
#> 2 <split [215/43]> Fold2
#> 3 <split [215/43]> Fold3
#> 4 <split [215/43]> Fold4
#> 5 <split [215/43]> Fold5
#> 6 <split [215/43]> Fold6

peng_rec <- 
  recipe(species ~ ., data=peng_train) %>%
  update_role(new_role = "id", island) %>%
  step_naomit(all_predictors(), all_outcomes()) %>%
  step_dummy(all_nominal(), -species)

peng_mod <- 
  multinom_reg(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet")

peng_wflow <- 
  workflow() %>%
  add_model(peng_mod) %>%
  add_recipe(peng_rec)

peng_grid <- grid_regular(penalty(), levels = 20)

peng_fit <-
  peng_wflow %>%
  tune_grid(
    resamples=folds,
    grid=peng_grid
  )
#> x Fold1: model 1/1 (predictions): Error: Problem with `mutate()` input `.row`.
#> x ...
#> x Fold2: model 1/1 (predictions): Error: Problem with `mutate()` input `.row`.
#> x ...
#> x Fold4: model 1/1 (predictions): Error: Problem with `mutate()` input `.row`.
#> x ...
#> x Fold5: model 1/1 (predictions): Error: Problem with `mutate()` input `.row`.
#> x ...
#> x Fold6: model 1/1 (predictions): Error: Problem with `mutate()` input `.row`.
#> x ...

peng_fit$.notes[[1]][[1]]
#> [1] "model 1/1 (predictions): Error: Problem with `mutate()` input `.row`.\nx Input `.row` can't be recycled to size 42.\nℹ Input `.row` is `orig_rows`.\nℹ Input `.row` must be size 42 or 1, not 43."
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note that adding `skip=TRUE` solves the issue (because glmnet can handle `NA`s?) and gives a warning: 
`model 1/1 (predictions): There are new levels in a factor: NA`

### PR DESCRIPTION
**Pull request by juliasilge**
Closes #241 

This PR adds an explicit check in `predict_model()` for whether all the original assessment rows are available, with a more direct error message:

``` r
library(tidymodels)

data(penguins)
set.seed(123)
peng_split <- initial_split(penguins, 
                            strata = species)

peng_train <- training(peng_split)
peng_test  <- testing(peng_split)

set.seed(345)
folds <- vfold_cv(peng_train, v = 6)
folds
#> #  6-fold cross-validation 
#> # A tibble: 6 x 2
#>   splits           id   
#>   <list>           <chr>
#> 1 <split [215/43]> Fold1
#> 2 <split [215/43]> Fold2
#> 3 <split [215/43]> Fold3
#> 4 <split [215/43]> Fold4
#> 5 <split [215/43]> Fold5
#> 6 <split [215/43]> Fold6

peng_rec <- 
  recipe(species ~ ., data=peng_train) %>%
  update_role(new_role = "id", island) %>%
  step_naomit(all_predictors(), all_outcomes()) %>%
  step_dummy(all_nominal(), -species)

peng_mod <- 
  multinom_reg(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet")

peng_wflow <- 
  workflow() %>%
  add_model(peng_mod) %>%
  add_recipe(peng_rec)

peng_fit <- tune_grid(peng_wflow, resamples = folds)
#> Loading required package: Matrix
#> 
#> Attaching package: 'Matrix'
#> The following objects are masked from 'package:tidyr':
#> 
#>     expand, pack, unpack
#> Loaded glmnet 4.0-2
#> x Fold1: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold2: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold3: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold4: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold5: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold6: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> Warning: All models failed. See the `.notes` column.

peng_fit$.notes[[1]][[1]]
#> [1] "preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set rows are not available at prediction time. Did your preprocessing steps filter or remove rows?"
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

This has been a source of confusion for users who don't understand why their tuning is failing.

Thoughts on the error message? 🤔

### CODE REVIEW

**Comment by juliasilge** [comment]
We may also want to add something to the documentation of row filtering recipe steps.

**Comment by DavisVaughan** [comment]
I like the message!

What should the user have done? i.e. in most of these cases should the user have set `skip = TRUE` on this kind of step to only apply it before the model is fit? If so, it might be worth mentioning something like: "If a recipe was used, consider using `skip = TRUE` on steps that remove rows to avoid calling them on the assessment set."

**Comment by juliasilge** [comment]
I changed this to check whether the workflow has a recipe and specialize the error message:

``` r
library(tidymodels)

data(penguins)
set.seed(123)
peng_split <- initial_split(penguins, 
                            strata = species)

peng_train <- training(peng_split)
peng_test  <- testing(peng_split)

set.seed(345)
folds <- vfold_cv(peng_train, v = 6)
folds
#> #  6-fold cross-validation 
#> # A tibble: 6 x 2
#>   splits           id   
#>   <list>           <chr>
#> 1 <split [215/43]> Fold1
#> 2 <split [215/43]> Fold2
#> 3 <split [215/43]> Fold3
#> 4 <split [215/43]> Fold4
#> 5 <split [215/43]> Fold5
#> 6 <split [215/43]> Fold6

peng_rec <- 
  recipe(species ~ ., data=peng_train) %>%
  update_role(new_role = "id", island) %>%
  step_naomit(all_predictors(), all_outcomes()) %>%
  step_dummy(all_nominal(), -species)

peng_mod <- 
  multinom_reg(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet")

peng_wflow <- 
  workflow() %>%
  add_model(peng_mod) %>%
  add_recipe(peng_rec)

peng_fit <- tune_grid(peng_wflow, resamples = folds)
#> Loading required package: Matrix
#> 
#> Attaching package: 'Matrix'
#> The following objects are masked from 'package:tidyr':
#> 
#>     expand, pack, unpack
#> Loaded glmnet 4.0-2
#> x Fold1: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold2: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold3: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold4: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold5: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> x Fold6: preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set ro...
#> Warning: All models failed. See the `.notes` column.

peng_fit$.notes[[1]][[1]]
#> [1] "preprocessor 1/1, model 1/1 (predictions): Error: Some assessment set rows are not available at prediction time. Consider using `skip = TRUE` on any recipe steps that remove rows to avoid calling them on the assessment set."
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I'm honestly not sure how this would happen with a formula preprocessor, but if it were to, somehow, the error message would be:

```out
Error: Some assessment set rows are not available at prediction time. Did your preprocessing steps filter or remove rows?
```

File: R/grid_helpers.R [hunk 1]
```diff
@@ -9,9 +9,23 @@ predict_model <- function(split, workflow, grid, metrics, submodels = NULL) {
   orig_rows <- as.integer(split, data = "assessment")
 
   if (length(orig_rows) != nrow(x_vals)) {
-    rlang::abort(paste0("Some assessment set rows are not available at ",
-                        "prediction time. Did your preprocessing steps ",
-                        "filter or remove rows?"))
+    msg <- paste0("Some assessment set rows are not available at ",
+                  "prediction time. ")
+
+    if (names(workflow$pre$actions) == "recipe") {
```
Comment (DavisVaughan) [inline R/grid_helpers.R:15]: You can use the `has_preprocessor_recipe()` helper here. I try to avoid digging into the workflow internals where possible, that way if they change we only have to update the helpers

Comment (juliasilge) [reply R/grid_helpers.R]: Ah, thanks for this reminder!
