### PR TITLE
Adjust and reformat survival predictions

### LINKED ISSUE #1073: tune failures with survival models with dynamic metrics
Currently, `tune_grid()` and company fail if a survival model is processed and measured with a dynamic metric: 

``` r
library(tidymodels)
library(censored)
#> Loading required package: survival
```

``` r

tidymodels_prefer()
theme_set(theme_bw())
options(pillar.advice = FALSE, pillar.min_title_chars = Inf)
```

``` r

set.seed(1)
sim_dat <- prodlim::SimSurv(500) %>%
  mutate(event_time = Surv(time, event)) %>%
  select(event_time, X1, X2)

set.seed(2)
split <- initial_split(sim_dat)
sim_tr <- training(split)
sim_te <- testing(split)
sim_rs <- vfold_cv(sim_tr)

time_points <- c(10, 1, 5, 15)

mod_spec <-
  proportional_hazards(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet") %>%
  set_mode("censored regression")

grid <- tibble(penalty = 10^c(-4, -2, -1))

gctrl <- control_grid(save_workflow = TRUE)

# standard setup end -------------------------------------------------------

sint_mtrc <- metric_set(brier_survival_integrated)

set.seed(2193)
grid_integrated_res <-
  mod_spec %>%
  tune_grid(
    event_time ~ X1 + X2,
    resamples = sim_rs,
    grid = grid,
    metrics = sint_mtrc,
    eval_time = time_points,
    control = gctrl
  )
#> → A | error:   The input should have a list column called ".pred".
#> Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
#> information.
```

<sup>Created on 2025-08-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by topepo**
Closes #1073 

Tests are in extratests.

### CODE REVIEW

File: R/loop_over_all_stages-helpers.R [hunk 1]
```diff
@@ -234,6 +234,9 @@ predict_all_types <- function(
 
   model_fit <- wflow_fit |> hardhat::extract_fit_parsnip()
 
+  # Will predictions have one value per row and should be in a list column?
+  dyn_types <- c("survival", "hazard", "quantile")
```
Comment (EmilHvitfeldt) [inline R/loop_over_all_stages-helpers.R]: a similar vector is created in `grid_helpers.R` line 74 in case we should consolidate

Comment (topepo) [reply R/loop_over_all_stages-helpers.R]: I consolidated them. Thanks
