### PR TITLE
verify that the 'metrics' argument is a metric set

### LINKED ISSUE #812: `int_pctl.tune_results()` errors with regression model
This should work, no? 

``` r
library(tidymodels)

set.seed(2193)
tune_res <-
  linear_reg(penalty = tune(), engine = "glmnet") %>%
  tune_grid(
    mpg ~ .,
    resamples = vfold_cv(mtcars, 2),
    metrics = metric_set(rmse),
    grid = 2,
    control = control_grid(save_pred = TRUE)
  )
int_pctl(tune_res, metrics = "rmse", times = 2)
#> Error in `purrr::map2()`:
#> ℹ In index: 1.
#> Caused by error in `check_tidy()`:
#> ! `statistics` should select a list column of tidy results.
```

<sup>Created on 2024-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by topepo**
For #813 and #812

Closes #812 

The error was due to an accidental wrong value type to `metrics.` We now give an informative error: 

``` r
library(tidymodels)

set.seed(2193)
tune_res <-
  linear_reg(penalty = tune(), engine = "glmnet") %>%
  tune_grid(
    mpg ~ .,
    resamples = vfold_cv(mtcars, 2),
    metrics = metric_set(rmse),
    grid = 2,
    control = control_grid(save_pred = TRUE)
  )
int_pctl(tune_res, metrics = "rmse", times = 2)
#> Error in `int_pctl()`:
#> ! `metrics` should be a yardstick `metric_set()`.
#> Backtrace:
#>     ▆
#>  1. ├─rsample::int_pctl(tune_res, metrics = "rmse", times = 2)
#>  2. └─tune:::int_pctl.tune_results(tune_res, metrics = "rmse", times = 2)
#>  3.   └─cli::cli_abort("{.arg metrics} should be a {.pkg yardstick} {.fun metric_set}.") at tune/R/int_pctl.R:89:7
#>  4.     └─rlang::abort(...)
```

<sup>Created on 2024-01-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It work for non-survival models: 

``` r
library(tidymodels)

set.seed(2193)
tune_res <-
    linear_reg(penalty = tune(), engine = "glmnet") %>%
    tune_grid(
        mpg ~ .,
        resamples = vfold_cv(mtcars, 2),
        metrics = metric_set(rmse),
        grid = 2,
        control = control_grid(save_pred = TRUE)
    )
int_pctl(tune_res, metrics = metric_set(rmse), times = 2)
#> Warning: Recommend at least 1000 non-missing bootstrap resamples for term `rmse`.
#> Recommend at least 1000 non-missing bootstrap resamples for term `rmse`.
#> # A tibble: 2 × 7
#>   .metric .estimator .lower .estimate .upper .config                 penalty
#>   <chr>   <chr>       <dbl>     <dbl>  <dbl> <chr>                     <dbl>
#> 1 rmse    bootstrap    3.92      4.33   4.73 Preprocessor1_Model1 0.00000109
#> 2 rmse    bootstrap    2.64      3.00   3.35 Preprocessor1_Model2 0.332
```

<sup>Created on 2024-01-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Still an issue though so I'll leave those #813 open and update there

``` r
library(tidymodels)
library(censored)
#> Loading required package: survival

lung_surv <- lung %>%
  dplyr::mutate(surv = Surv(time, status), .keep = "unused")

set.seed(2193)
tune_res <-
  proportional_hazards(penalty = tune(), engine = "glmnet") %>%
  tune_grid(
    surv ~ .,
    resamples = vfold_cv(lung_surv, 2),
    grid = 2,
    control = control_grid(save_pred = TRUE),
    metrics = metric_set(concordance_survival, brier_survival_integrated),
    eval_time = c(10, 20)
  )
foo <- int_pctl(tune_res, times = 2, metrics = metric_set(brier_survival_integrated), eval_time = 10)
#> Warning: The 'eval_time' argument is not needed for this data set.
#> Warning: Unknown or uninitialised column: `.eval_time`.
#> Error in `purrr::map2()`:
#> ℹ In index: 1.
#> Caused by error in `dplyr::rename()`:
#> ! Can't rename columns that don't exist.
#> ✖ Column `term` doesn't exist.
#> Backtrace:
#>      ▆
#>   1. ├─rsample::int_pctl(...)
#>   2. ├─tune:::int_pctl.tune_results(...)
#>   3. │ ├─... %>% dplyr::arrange(.config, .metric) at tune/R/int_pctl.R:93:3
#>   4. │ └─purrr::map2(...)
#>   5. │   └─purrr:::map2_("list", .x, .y, .f, ..., .progress = .progress)
#>   6. │     ├─purrr:::with_indexed_errors(...)
#>   7. │     │ └─base::withCallingHandlers(...)
#>   8. │     ├─purrr:::call_with_cleanup(...)
#>   9. │     └─tune (local) .f(.x[[i]], .y[[i]], ...)
#>  10. │       └─tune:::boostrap_metrics_by_config(...)
#>  11. │         └─... %>% cbind(config) at tune/R/int_pctl.R:136:3
#>  12. ├─dplyr::arrange(., .config, .metric)
#>  13. ├─purrr::list_rbind(.)
#>  14. │ └─purrr:::check_list_of_data_frames(x)
#>  15. │   └─vctrs::vec_check_list(x, call = error_call)
#>  16. │     └─vctrs::obj_check_list(x, ..., arg = arg, call = call)
#>  17. ├─base::cbind(., config)
#>  18. ├─dplyr::select(., -.alpha, -.method)
#>  19. ├─dplyr::relocate(., .estimator, .after = .metric)
#>  20. ├─dplyr::rename(., .metric = term)
#>  21. ├─dplyr:::rename.data.frame(., .metric = term)
#>  22. │ └─tidyselect::eval_rename(expr(c(...)), .data)
#>  23. │   └─tidyselect:::rename_impl(...)
#>  24. │     └─tidyselect:::eval_select_impl(...)
#>  25. │       ├─tidyselect:::with_subscript_errors(...)
#>  26. │       │ └─rlang::try_fetch(...)
#>  27. │       │   └─base::withCallingHandlers(...)
#>  28. │       └─tidyselect:::vars_select_eval(...)
#>  29. │         └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
#>  30. │           └─tidyselect:::eval_c(expr, data_mask, context_mask)
#>  31. │             └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
#>  32. │               └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
#>  33. │                 └─tidyselect:::as_indices_sel_impl(...)
#>  34. │                   └─tidyselect:::as_indices_impl(...)
#>  35. │                     └─tidyselect:::chr_as_locations(x, vars, call = call, arg = arg)
#>  36. │                       └─vctrs::vec_as_location(...)
#>  37. └─vctrs (local) `<fn>`()
#>  38.   └─vctrs:::stop_subscript_oob(...)
#>  39.     └─vctrs:::stop_subscript(...)
#>  40.       └─rlang::abort(...)
```

<sup>Created on 2024-01-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/int_pctl.R [hunk 1]
```diff
@@ -84,6 +84,10 @@ int_pctl.tune_results <- function(.data, metrics = NULL, times = 1001,
 
   if (is.null(metrics)) {
     metrics <- .get_tune_metrics(.data)
+  } else {
+    if (!inherits(metrics, "metric_set")) {
+      cli::cli_abort("{.arg metrics} should be a {.pkg yardstick} {.fun metric_set}.")
```
Comment (hfrick) [inline R/int_pctl.R:89]:
```suggestion
      cli::cli_abort("{.arg metrics} should be a metric set as generated by {.fun yardstick::metric_set}.")
```
Namespacing the function makes the error message clickable in RStudio which I think is pretty neat.

**Review by hfrick — APPROVED** [review]
Ah, user error 🙈 😆  I obviously think that this error message is a great idea! 😄
