### PR TITLE
Fit resampled calbration model on correct submodel predictions

### LINKED ISSUE #1144: For submodels, resampled calibration models are not trained on the correct predictions
When tuning a model that has both a submodel parameter (e.g., `penalty` in glmnet) and a postprocessor that requires fitting (e.g., probability calibration via tailor), all calibration models are trained on predictions made with the same (and thus usually wrong) submodel parameter value.

The loop correctly generates assessment-set predictions for all submodel values at once via `multi_predict()` and filters them per iteration. But when fitting the postprocessor, `finalize_fit_post()` calls `workflows::.fit_post()`, which internally calls `augment(workflow_mock, calibration_data)` → `predict()`. This predict call uses the submodel parameter value from the model spec — which is whatever `min_grid()` chose for fitting, not the value for the current predict iteration.

``` r
library(tidymodels)

set.seed(1)
dat <- modeldata::sim_regression(500)

dat_split <- initial_validation_split(dat)
dat_rs <- validation_set(dat_split)

cal_post <- tailor() |>
  adjust_numeric_calibration()
glmn_spec <- linear_reg(penalty = tune(), mixture = 1) |>
  set_engine("glmnet")
wflow <- workflow(outcome ~ ., glmn_spec, cal_post)

# A small grid with well-separated penalty values
grd <- tibble::tibble(penalty = c(0.001, 0.1))

set.seed(1)
tune_res <- tune_grid(
  wflow,
  resamples = dat_rs,
  metrics = metric_set(rmse),
  grid = grd,
  control = control_grid(
    extract = function(wf) {
      # Extract the fitted calibration model for inspection
      extract_postprocessor(wf, estimated = TRUE)
    }
  )
)
#> Registered S3 method overwritten by 'butcher':
#>   method                 from    
#>   as.character.dev_topic generics

extracts <- collect_extracts(tune_res)

cal_coef_1 <- extracts$.extracts[[1]]$adjustments[[1]]$results$fit$estimates[[1]]$estimate |>
  coefficients()
cal_coef_2 <- extracts$.extracts[[2]]$adjustments[[1]]$results$fit$estimates[[1]]$estimate |>
  coefficients()

identical(cal_coef_1, cal_coef_2)
#> [1] TRUE
```

<sup>Created on 2026-03-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by hfrick**
closes #1144

Instead of letting `.fit_post()` generate calibration predictions, we now pre-compute them ourselves using the same `predict_all_types()` machinery that handles assessment predictions. For submodels, this predicts all values at once via `multi_predict()`, then filters per iteration — mirroring how assessment predictions already work.

### CODE REVIEW

File: R/loop_over_all_stages-helpers.R [hunk 1]
```diff
@@ -198,19 +202,44 @@ finalize_fit_post <- function(wflow_current, data_calibration, grid = NULL) {
     finalize_tailor(grid)
   wflow_current <- set_workflow_tailor(wflow_current, post_obj)
 
-  workflows::.fit_post(wflow_current, data_calibration)
+  fit_post_from_predictions(wflow_current, predictions_calibration)
+}
+
+# This mimics `.fit_post()`, except it takes predictions instead of the
```
Comment (hfrick) [inline R/loop_over_all_stages-helpers.R]: I'm not loving that we now break up the pattern of calling `.fit_<workflow_stage>()` but I think it's valuable here. I'm taking this as an indication that maybe we should change workflows to reflect that.

File: R/loop_over_all_stages.R [hunk 2]
```diff
@@ -102,10 +123,6 @@
 
     grid_with_pre <- current_grid
 
-    if (is_failure(pred_data)) {
-      next
-    }
-
```
Comment (hfrick) [inline R/loop_over_all_stages.R:108]: This is still around, I only moved it up to line 89 so that we "fail early", i.e., go to the next iteration of the loop immediately if the calculation of `pred_data` fails.

File: R/loop_over_all_stages.R [hunk 3]
```diff
@@ -209,6 +251,38 @@
         has_post <- has_tailor(current_wflow)
         num_iterations_post <- max(nrow(current_sched_pred$post_stage[[1]]), 1)
 
+        # if the postprocessor does not require a fit,
+        # this does not cause data leakage
+        current_cal_pred <- current_pred
```
Comment (hfrick) [inline R/loop_over_all_stages.R:256]:
```suggestion
        # if the postprocessor does not require a fit,
        # this does not cause data leakage
        current_cal_pred <- current_pred
        
```

Adding an empty line to make it more obvious that the comment only applies to line 256

File: R/loop_over_all_stages-helpers.R [hunk 4]
```diff
@@ -189,7 +189,11 @@ has_tailor_estimated <- function(x) {
 # ------------------------------------------------------------------------------
 # Prediction and postprocessing
 
-finalize_fit_post <- function(wflow_current, data_calibration, grid = NULL) {
+finalize_fit_post <- function(
+  wflow_current,
+  predictions_calibration,
```
Comment (EmilHvitfeldt) [inline R/loop_over_all_stages-helpers.R:194]: I like the name change here

File: R/loop_over_all_stages-helpers.R [hunk 5]
```diff
@@ -198,19 +202,44 @@ finalize_fit_post <- function(wflow_current, data_calibration, grid = NULL) {
...
+
+  post_fit <- tailor::fit(
+    object = tailor_obj,
+    .data = predictions_calibration,
+    outcome = outcome_names,
+    estimate = tidyselect::any_of(c(".pred", ".pred_class")),
+    probabilities = c(
+      tidyselect::contains(".pred_"),
+      -tidyselect::matches("^\\.pred$|^\\.pred_class$")
+    )
```
Comment (EmilHvitfeldt) [inline R/loop_over_all_stages-helpers.R:224]: Maybe this isn't the PR where we do this, but I'm starting to think we need some pred name helpers. Because I'm pretty sure that this selects for `.pred_time`

**Review by EmilHvitfeldt — APPROVED** [review]

File: R/loop_over_all_stages-helpers.R (hunk 5 above)
Comment (hfrick) [reply R/loop_over_all_stages-helpers.R:224]: I agree. This is taken from workflows, so that'd be the better place to put that. We also have not yet implemented postprocessing for censored regression models.

File: R/loop_over_all_stages-helpers.R (hunk 4 above)
Comment (hfrick) [reply R/loop_over_all_stages-helpers.R:194]: `data_calibration` is the argument of the workflows machinery so keeping it would have been pretty confusing 😄

File: R/loop_over_all_stages-helpers.R (hunk 1 above)
Comment (topepo) [inline R/loop_over_all_stages-helpers.R]:
```suggestion
# This mimics `workflows::.fit_post()`, except it takes predictions instead of the
```

File: R/loop_over_all_stages-helpers.R (hunk 5 above)
Comment (topepo) [reply R/loop_over_all_stages-helpers.R:224]: https://github.com/tidymodels/parsnip/issues/1353

**Review by topepo — COMMENTED** [review]
Looks great.
