### PR TITLE
catch and log `extract` issues

### LINKED ISSUE #565: balancing verbosity for errors and warnings
The defaults for tune's verbosity for raising errors and warnings feel a bit out of balance to me. In the case of errors that occur outside of `.catch_and_log` but inside of `super_safely` machinery, I think we especially ought to reconsider how we pass along prompts.

``` r
library(tune)

packageVersion("tune")
#> [1] '1.0.1'
```

## At fit time

On warnings inside `.catch_and_log`, tune both prints warnings out and collapses them at print of the resulting object.

``` r
# on warn at fit time:
res_fit_warn <-
  fit_resamples(
    parsnip::linear_reg(engine = "glmnet", penalty = 100),
    mpg ~ .,
    rsample::bootstraps(mtcars, 3)
  )
#> ! Bootstrap1: internal: A correlation computation is required, but `estimate` is constant and ha...
#> ! Bootstrap2: internal: A correlation computation is required, but `estimate` is constant and ha...
#> ! Bootstrap3: internal: A correlation computation is required, but `estimate` is constant and ha...

res_fit_warn
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 3 × 4
#>   splits          id         .metrics         .notes          
#>   <list>          <chr>      <list>           <list>          
#> 1 <split [32/10]> Bootstrap1 <tibble [2 × 4]> <tibble [1 × 3]>
#> 2 <split [32/10]> Bootstrap2 <tibble [2 × 4]> <tibble [1 × 3]>
#> 3 <split [32/11]> Bootstrap3 <tibble [2 × 4]> <tibble [1 × 3]>
#> 
#> There were issues with some computations:
#> 
#>   - Warning(s) x3: A correlation computation is required, but `estimate` is constant...
#> 
#> Run `show_notes(.Last.tune.result)` for more information.
```

On fit failure, the functions error out.

``` r
# on fail at fit time:
res_fit_fail <-
  fit_resamples(
    parsnip::boost_tree(engine = "lightgbm", mode = "regression"),
    mpg ~ .,
    rsample::bootstraps(mtcars, 3)
  )
#> Error:
#> ! parsnip could not locate an implementation for `boost_tree` regression
#>   model specifications using the `lightgbm` engine.
#> ℹ The parsnip extension package bonsai implements support for this
#>   specification.
#> ℹ Please install (if needed) and load to continue.
```

This escalation feels good.👍

## Outside of `.catch_and_log`

Outside of fit time (e.g. at `extract`), this handling looks a bit different.

Warnings are printed during fitting and summarized at print, as before:

``` r
# warn at extract time
res_extract_warn <-
  fit_resamples(
    parsnip::linear_reg(),
    mpg ~ .,
    rsample::bootstraps(mtcars, 3),
    control = control_resamples(extract = function(x) {warning("AHHH")})
  )
#> ! Bootstrap1: internal: AHHH
#> ! Bootstrap2: internal: AHHH
#> ! Bootstrap3: internal: AHHH

res_extract_warn
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 3 × 5
#>   splits          id         .metrics         .notes           .extracts       
#>   <list>          <chr>      <list>           <list>           <list>          
#> 1 <split [32/10]> Bootstrap1 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 2 <split [32/14]> Bootstrap2 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 3 <split [32/14]> Bootstrap3 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 
#> There were issues with some computations:
#> 
#>   - Warning(s) x3: AHHH
#> 
#> Run `show_notes(.Last.tune.result)` for more information.
```

Failures are hidden during both fitting and printing.

``` r
# fail at extract time
res_extract_fail <-
  fit_resamples(
    parsnip::linear_reg(),
    mpg ~ .,
    rsample::bootstraps(mtcars, 3),
    control = control_resamples(extract = function(x) {stop("AHHH")})
  )

res_extract_fail
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 3 × 5
#>   splits          id         .metrics         .notes           .extracts       
#>   <list>          <chr>      <list>           <list>           <list>          
#> 1 <split [32/11]> Bootstrap1 <tibble [2 × 4]> <tibble [0 × 3]> <tibble [1 × 2]>
#> 2 <split [32/14]> Bootstrap2 <tibble [2 × 4]> <tibble [0 × 3]> <tibble [1 × 2]>
#> 3 <split [32/13]> Bootstrap3 <tibble [2 × 4]> <tibble [0 × 3]> <tibble [1 × 2]>
```

I would propose:

* For warnings, regardless of context, raise the current print summary "There were issues with some computations" at both execution and print time. With `verbose = TRUE`, output should mirror the current defaults + additionally pass along messages.
* Handle errors at fit time as they are currently.
* Handle errors outside of fit time in the same way as warnings. If errors occur after `fit`, the output may still be usable, though even if the user would ultimately decide re-run the computations, the majority of the computationally intensive bits are finished, so we're not wasting user's time by running to completion. 

This may oversimplify the technical minutae of tune's error handling, but I think this is as complex as the story should be as it relates to user interface.

Any thoughts, @DavisVaughan, @topepo, @hfrick, and/or @EmilHvitfeldt?

<sup>Created on 2022-10-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by simonpcouch**
With CRAN tune, the package hides errors that occur with mis-specified `extract` functions:

``` r
library(tidymodels)

wf <- workflow(mpg ~ ., linear_reg())
set.seed(1)
boots <- bootstraps(mtcars, 3)

# warn at extract --------------------------------------------------------------
raise_warning <- function(x) {warning("AHHH"); TRUE}

res_extract_warn <-
  fit_resamples(
    wf, boots, control = control_resamples(extract = raise_warning)
  )
#> ! Bootstrap1: internal: AHHH
#> ! Bootstrap2: internal: AHHH
#> ! Bootstrap3: internal: AHHH

res_extract_warn
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 3 × 5
#>   splits          id         .metrics         .notes           .extracts       
#>   <list>          <chr>      <list>           <list>           <list>          
#> 1 <split [32/13]> Bootstrap1 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 2 <split [32/17]> Bootstrap2 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 3 <split [32/11]> Bootstrap3 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 
#> There were issues with some computations:
#> 
#>   - Warning(s) x3: AHHH
#> 
#> Run `show_notes(.Last.tune.result)` for more information.

# error at extract -------------------------------------------------------------
raise_error <- function(x) {stop("AHHH"); TRUE}

res_extract_error <-
  fit_resamples(
    wf, boots, control = control_resamples(extract = raise_error)
  )

res_extract_error
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 3 × 5
#>   splits          id         .metrics         .notes           .extracts       
#>   <list>          <chr>      <list>           <list>           <list>          
#> 1 <split [32/13]> Bootstrap1 <tibble [2 × 4]> <tibble [0 × 3]> <tibble [1 × 2]>
#> 2 <split [32/17]> Bootstrap2 <tibble [2 × 4]> <tibble [0 × 3]> <tibble [1 × 2]>
#> 3 <split [32/11]> Bootstrap3 <tibble [2 × 4]> <tibble [0 × 3]> <tibble [1 × 2]>

res_extract_error$.extracts[[1]]$.extracts
#> [[1]]
#> [1] "Error in extractor(object) : AHHH\n"
#> attr(,"class")
#> [1] "try-error"
#> attr(,"condition")
#> <simpleError in extractor(object): AHHH>
```

<sup>Created on 2022-11-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

With this PR, the package surfaces `extract`ion errors in the same way that it does errors that occur elsewhere:

``` r
library(tidymodels)

wf <- workflow(mpg ~ ., linear_reg())
set.seed(1)
boots <- bootstraps(mtcars, 3)

# warn at extract --------------------------------------------------------------
raise_warning <- function(x) {warning("AHHH"); TRUE}

res_extract_warn <-
  fit_resamples(
    wf, boots, control = control_resamples(extract = raise_warning)
  )
#> ! Bootstrap1: preprocessor 1/1, model 1/1 (extracts): AHHH
#> ! Bootstrap2: preprocessor 1/1, model 1/1 (extracts): AHHH
#> ! Bootstrap3: preprocessor 1/1, model 1/1 (extracts): AHHH

res_extract_warn
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 3 × 5
#>   splits          id         .metrics         .notes           .extracts       
#>   <list>          <chr>      <list>           <list>           <list>          
#> 1 <split [32/13]> Bootstrap1 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 2 <split [32/17]> Bootstrap2 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 3 <split [32/11]> Bootstrap3 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 
#> There were issues with some computations:
#> 
#>   - Warning(s) x3: AHHH
#> 
#> Run `show_notes(.Last.tune.result)` for more information.

# error at extract -------------------------------------------------------------
raise_error <- function(x) {stop("AHHH"); TRUE}

res_extract_error <-
  fit_resamples(
    wf, boots, control = control_resamples(extract = raise_error)
  )
#> x Bootstrap1: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH
#> x Bootstrap2: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH
#> x Bootstrap3: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH

res_extract_error
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 3 × 5
#>   splits          id         .metrics         .notes           .extracts
#>   <list>          <chr>      <list>           <list>           <list>   
#> 1 <split [32/13]> Bootstrap1 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>
#> 2 <split [32/17]> Bootstrap2 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>   
#> 3 <split [32/11]> Bootstrap3 <tibble [2 × 4]> <tibble [1 × 3]> <tibble [1 × 2]>   
#> 
#> There were issues with some computations:
#> 
#>   - Error(s) x3: Error in extractor(object): AHHH
#> 
#> Run `show_notes(.Last.tune.result)` for more information.

# both warn and error at extract
raise_both <- function(x) {warning("AH"); stop("AHHH"); TRUE}

res_extract_both <-
  fit_resamples(
    wf, boots, control = control_resamples(extract = raise_both)
  )
#> ! Bootstrap1: preprocessor 1/1, model 1/1 (extracts): AH
#> x Bootstrap1: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH
#> ! Bootstrap2: preprocessor 1/1, model 1/1 (extracts): AH
#> x Bootstrap2: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH
#> ! Bootstrap3: preprocessor 1/1, model 1/1 (extracts): AH
#> x Bootstrap3: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH

res_extract_both
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 3 × 5
#>   splits          id         .metrics         .notes           .extracts
#>   <list>          <chr>      <list>           <list>           <list>   
#> 1 <split [32/13]> Bootstrap1 <tibble [2 × 4]> <tibble [2 × 3]> <tibble [1 × 2]>   
#> 2 <split [32/17]> Bootstrap2 <tibble [2 × 4]> <tibble [2 × 3]> <tibble [1 × 2]>   
#> 3 <split [32/11]> Bootstrap3 <tibble [2 × 4]> <tibble [2 × 3]> <tibble [1 × 2]>   
#> 
#> There were issues with some computations:
#> 
#>   - Error(s) x3: Error in extractor(object): AHHH
#>   - Warning(s) x3: AH
#> 
#> Run `show_notes(.Last.tune.result)` for more information.
```

<sup>Created on 2022-11-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Fixes #565, to the extent that we will. :)

### CODE REVIEW

File: R/tune_results.R [hunk 1]
```diff
@@ -66,6 +66,7 @@ summarize_notes <- function(x) {
     dplyr::group_nest(type) %>%
     dplyr::mutate(data = purrr::map(data, ~ dplyr::count(.x, note))) %>%
     tidyr::unnest(data) %>%
+    dplyr::rowwise() %>%
```
Comment (simonpcouch) [inline R/tune_results.R:69]: The changes in this file fix a bug in `summarize_notes()` where the condition messages for warnings and errors were pasted if there were multiple distinct notes. I indulged myself and went ahead and made this fix so that we could snapshot test that case well, but committed those changes separately so that we could document what that test output looks like without those changes.

File: tests/testthat/_snaps/extract.md [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+
+---
+
+    Code
+      res_extract_error <- fit_resamples(wf, boots, control = control_resamples(
+        extract = raise_error))
+    Message
+      x Bootstrap1: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH
+      x Bootstrap2: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH
+      x Bootstrap3: preprocessor 1/1, model 1/1 (extracts): Error in extractor(object): AHHH
```
Comment (simonpcouch) [inline tests/testthat/_snaps/extract.md:19]: I'd like to make these `Error in extractor(object)` bits of the error messages more informative, but that would require changes to more general machinery (and many snapshot updates) that would be better off living in a separate PR.

File: R/pull.R [hunk 3]
```diff
@@ -23,9 +23,9 @@ pulley <- function(resamples, res, col) {
 
   id_cols <- grep("^id", names(resamples), value = TRUE)
   resamples <- dplyr::arrange(resamples, !!!syms(id_cols))
-  pulled_vals <- purrr::map_dfr(res, ~ .x[[col]])
+  pulled_vals <- try(purrr::map_dfr(res, ~ .x[[col]]), silent = TRUE)
```
Comment (simonpcouch) [inline R/pull.R:26]: The addition of the `try` here counteracts the deletion of the `try` at line 6, which is needed to surface the errors that occur at line 6 to `.catch_and_log()`.

File: R/pull.R [hunk 4]
```diff
@@ -191,14 +191,8 @@ append_predictions <- function(collection, predictions, split, control, .config
...
-  extracts <-
-    grid %>%
-    dplyr::bind_cols(labels(split)) %>%
-    mutate(
-      .extracts = list(
-        extract_details(workflow, ctrl$extract)
-      )
-    )
+  extracts <- dplyr::bind_cols(grid, labels(split))
+  extracts$.extracts <- list(extract_details(workflow, ctrl$extract))
```
Comment (simonpcouch) [inline R/pull.R:195]: `mutate()` wraps the raised errors with information that, when collapsed by tune's machinery, obscures the condition messages raised from the extractor functions themselves.

File: NEWS.md [hunk 5]
```diff
@@ -2,6 +2,8 @@
 
 * Fixed bug in `select_by_pct_loss()` where the model with the greatest loss within the limit was returned rather than the most simple model whose loss was within the limit. (#543)
 
+* Improves condition handling for errors that occur during extraction from workflows. While messages and warnings were appropriately handled, errors occurring due to mis-specified `extract()` functions being supplied to `control_*()` functions were silently caught. As with warnings, errors are now surfaced both during execution and at `print()`.
```
Comment (DavisVaughan) [inline NEWS.md:5]:
```suggestion
* Improves condition handling for errors that occur during extraction from workflows. While messages and warnings were appropriately handled, errors occurring due to mis-specified `extract()` functions being supplied to `control_*()` functions were silently caught. As with warnings, errors are now surfaced both during execution and at `print()` (#575).
```

**Review by DavisVaughan — APPROVED** [review]
Looks good!
